; generated by ARM/Thumb C/C++ Compiler, RVCT3.1 [Build 569]
; commandline armcc [-S test.c]
        ARM
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

||sum|| PROC
        ADD      r0,r0,r1
        BX       lr
        ENDP

max PROC
        CMP      r0,r1
        MOVLE    r0,r1
        BX       lr
        ENDP

main PROC
        MOV      r0,#0xe
        BX       lr
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT ||sum||
        EXPORT max
        EXPORT main

        IMPORT ||Lib$$Request$$armlib|| [WEAK]

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {FALSE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
